#ifndef PQCLEAN_DILITHIUM2_MASK_OPTMEM_PARAMS_H
#define PQCLEAN_DILITHIUM2_MASK_OPTMEM_PARAMS_H



#define SEEDBYTES 32
#define CRHBYTES 64
#define N 256
#define Q 8380417
#define D 13
#define ROOT_OF_UNITY 1753

#define K 4
#define L 4
#define ETA 2
#define TAU 39
#define BETA 78
#define GAMMA1 (1 << 17)
#define GAMMA2 ((Q-1)/88)
#define OMEGA 80
#define PQCLEAN_DILITHIUM2_MASK_OPTMEM_CRYPTO_ALGNAME "Dilithium2"

#define QP 257

#define NSHARES 2

/* Maximum value encountered in dilithium versions */
#define TAU_MAX 60 

#define POLY_BYTES N * 4
#define POLYVECK_BYTES K * POLY_BYTES
#define POLYVECL_BYTES L * POLY_BYTES
#define MAT_BYTES L * K * POLY_BYTES

#define POLYT1_PACKEDBYTES  320
#define POLYT0_PACKEDBYTES  416
#define POLYVECH_PACKEDBYTES (OMEGA + K)

#define POLYZ_PACKEDBYTES   576

#define POLYW1_PACKEDBYTES  192

#define POLYETA_PACKEDBYTES  96

#define PQCLEAN_DILITHIUM2_MASK_OPTMEM_CRYPTO_PUBLICKEYBYTES (SEEDBYTES + K*POLYT1_PACKEDBYTES)
#define PQCLEAN_DILITHIUM2_MASK_OPTMEM_CRYPTO_SECRETKEYBYTES (3*SEEDBYTES \
        + NSHARES*L*POLYETA_PACKEDBYTES \
        + NSHARES*K*POLYETA_PACKEDBYTES \
        + K*POLYT0_PACKEDBYTES)
#define PQCLEAN_DILITHIUM2_MASK_OPTMEM_CRYPTO_BYTES (SEEDBYTES + L*POLYZ_PACKEDBYTES + POLYVECH_PACKEDBYTES)

#define PQCLEAN_DILITHIUM2_MASK_OPTMEM_GEN_BUF_BYTES (2*SEEDBYTES + CRHBYTES + 2*POLYVECL_BYTES + 2*POLYVECK_BYTES + MAT_BYTES + POLY_BYTES)
#define PQCLEAN_DILITHIUM2_MASK_OPTMEM_SIGN_BUF_BYTES (MAT_BYTES + 4*POLYVECK_BYTES + 3*POLYVECK_BYTES + 2*CRHBYTES + POLY_BYTES + 344)
#define PQCLEAN_DILITHIUM2_MASK_OPTMEM_VER_BUF_BYTES (SEEDBYTES + CRHBYTES + 3*POLYVECK_BYTES + POLYVECL_BYTES + 2*POLY_BYTES + MAT_BYTES)

#endif
